// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYtBnGdDZJ2ouFk1Nb1c3tYm_b5H_O1g',
    appId: '1:507150159212:web:63349bd3dd09bc3e17f749',
    messagingSenderId: '507150159212',
    projectId: 'study-1-f0b78',
    authDomain: 'study-1-f0b78.firebaseapp.com',
    storageBucket: 'study-1-f0b78.appspot.com',
    measurementId: 'G-P6YQEQQJTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCol7zzoGG1_2mldL9KqUhUo8jElqoF-Hw',
    appId: '1:507150159212:android:22a6349de855cb2317f749',
    messagingSenderId: '507150159212',
    projectId: 'study-1-f0b78',
    storageBucket: 'study-1-f0b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUk4-TNj-9IaB-Hjwe-8BuYWFrcvIw9Hk',
    appId: '1:507150159212:ios:939b3762943839aa17f749',
    messagingSenderId: '507150159212',
    projectId: 'study-1-f0b78',
    storageBucket: 'study-1-f0b78.appspot.com',
    iosBundleId: 'com.example.studyf1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUk4-TNj-9IaB-Hjwe-8BuYWFrcvIw9Hk',
    appId: '1:507150159212:ios:939b3762943839aa17f749',
    messagingSenderId: '507150159212',
    projectId: 'study-1-f0b78',
    storageBucket: 'study-1-f0b78.appspot.com',
    iosBundleId: 'com.example.studyf1',
  );

}